/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if dc1394_dma_setup_capture needs the extra_buffering argument.
   */
/* #undef DC1394_EXTRA_BUFFERING_FLAG */

/* Define to 1 if you have the <asm/types.h> header file. */
#define HAVE_ASM_TYPES_H 1

/* Define to 1 if you have the <go7007.h> header file. */
/* #undef HAVE_GO7007_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <linux/compiler.h> header file. */
/* #undef HAVE_LINUX_COMPILER_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <pwc-ioctl.h> header file. */
/* #undef HAVE_PWC_IOCTL_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "spook"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "Spook"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Spook 20050207"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "spook"

/* Define to the version of this package. */
#define PACKAGE_VERSION "20050207"

/* Define to include the encoder-jpeg module. */
#define SPOOK_ENCODER_JPEG 1

/* Define to include the encoder-mpeg4 module. */
/* #undef SPOOK_ENCODER_MPEG4 */

/* Define to include the input-dc1394 module. */
/* #undef SPOOK_INPUT_DC1394 */

/* Define to include the input-v4l module. */
/* #undef SPOOK_INPUT_V4L */

/* Define to include the input-v4l2 module. */
#define SPOOK_INPUT_V4L2 1

/* Define to include the input-vdig module. */
/* #undef SPOOK_INPUT_VDIG */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "20050207"

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1
